### PR TITLE
Project pages

### LINKED ISSUE #117: Update premium plugins
Update search/filter pro plugin and twitter feeds

### PR DESCRIPTION
**Pull request by cjyabraham**
[Projects page on PR site](https://pr-118-lfph.pantheonsite.io/join/projects/)

Also created a project listing on [the homepage](https://pr-118-lfph.pantheonsite.io/) to satisfy [this request](https://github.com/lfph/lfph.io/issues/114).

### CODE REVIEW

**Comment by thetwopct** [comment]
1. As there are currently 5 projects, would it make more sense to style the home page block to have 5 columns?

CleanShot 2022-05-23 at 10 59 20@2x

2. I understand the request from the team was to "embed the landscape" but maybe the goal was to "show LFPH members" - embedding the landscape has quite a rigid design, doesn't quite align with other elements on the page, and has issues if a member is clicked on when the embed is not 100% in focus (the modal opens up off-screen). I wonder if we can re-use the code we use on CNCF to extract members in a JSON format which will allow us to display them how we want? 

CleanShot 2022-05-23 at 11 01 30@2x

3. Accepted text on the project sub page needs to be updated to LFPH
CleanShot 2022-05-23 at 11 05 40@2x

**Comment by cjyabraham** [comment]
1. Sure. Done.
2. Yes, what you suggest is an option, however, I'm wanting to see what kind of reaction we get from the team on this first pass before investing more time to import member data etc. They change their minds a lot so don't want to spend all that time until things are more certain.
3. Fixed.

**Review by thetwopct — APPROVED** [review]
I took this opportunity to update some packages and refine the build process based on the changes we had done for CNCF (i.e. browsersync / npm all via Lando). This should remove the dependabot security alerts we get.

**Comment by cjyabraham** [comment]
Sweet. Thanks. Good to get all the build processes consistent.

**Pull request merged**
