### PR TITLE
Adding Slack Icon to footer, Flying Scripts testing for SFMC forms

### PR DESCRIPTION
**Pull request by thetwopct**
- I've added a Slack option to the Global Settings options in LF MU plugin, then updated the plugin here
- Added the corresponding SVG code to the footer for the site
- Unbundled SFMC-Forms.js, added to 'third-party' directory and enqueued with a recaptcha dependency
- Need to activate Flying Scripts plugin and add the following as scripts to delay:

ctf-scripts
recaptcha__en
api.js
sfmc-forms

### CODE REVIEW

**Comment by thetwopct** [comment]
Slack in footer:

20200721112111-Linux Foundation Public Health - Collaborating to battle COVID-19

Forms:

I'm seeing this error on submit:

`Error: No reCAPTCHA clients exist.`

I'm not sure if this is the domain being incorrect with recapctcha, or still a problem with delaying the script. The JS is loaded and is in the resources, and seems to be in the right order. Could you take a look and let me know your thoughts?

FYI, I did make the SFMC form dependent on recaptcha loading, which makes sense to me, but may affect its working (in class-enqueue.php)

```
// SalesForce Forms customization.
			wp_enqueue_script( 'sfmc-forms', get_template_directory_uri() . '/source/js/third-party/sfmc-forms.js', array( 'jquery', 'recaptcha' ), filemtime( get_template_directory() . '/source/js/third-party/sfmc-forms.js' ), true );
```

**Comment by cjyabraham** [comment]
I have to whitelist each domain for recaptcha.  I've done that now and now the form is producing a different error: "Uncaught (in promise)".

**Comment by thetwopct** [comment]
Using my local site (https://lfph.lndo.site) I'm unable to reproduce errors now. But on the PR, it's always errors. Even with Flying Scripts turned off (but with sfmc-forms enqueued separately), I'm getting:

"Unhandled Promise Rejection: null"

I think this may be null as I am not sure if sfmc-forms handles the promise error return correctly. But from a Google search it seems this error is common when the site has not been added to Recaptcha.

**Comment by cjyabraham** [comment]
I have this working now with the above commit.  There was some race condition happening due to the fact that document.ready and window.onload were already true so the code in those functions was sometimes getting executed prior to the code in the init function (normally it would have been the opposite).

Note that I don't think this script will work properly now _unless_ it is delayed with flying scripts.

Do you want to test it and make sure it's good?

**Comment by cjyabraham** [comment]
I have been testing this on various devices.  These ones worked:
- iOS Safari
- iPhone
- FF on Windows
- Samsang A50S

These failed with `Uncaught TypeError: grecaptcha.render is not a function` from line 79:
- Galaxy S20 (Subscribe refreshed the whole page, therefore js didn't run); some subsequent tests worked properly
- Galaxy S10
- FF on Windows didn't work for the newsletter form

**Comment by cjyabraham** [comment]
FYI, I did a quick [performance test to prove that this was worth doing](https://docs.google.com/spreadsheets/d/1-YU77OLcdI1mMPRpK6FEjkKS8DMl2m7uuGo0i92iiu8/edit#gid=161007827).

**Comment by cjyabraham** [comment]
This should now all work.  The one case in which it does not work is when you have a very slow connection and speed to fill in the form prior to the scripts running, however, I think this would have been a problem without Flying Scripts anyway.

**Comment by cjyabraham** [comment]
Note: I turned off the Flying Scripts plugin and the forms still do work which is good!

**Comment by cjyabraham** [comment]
@thetwopct can you do some testing on this to see if you can break it.  If not, I will merge and deploy.

**Comment by cjyabraham** [comment]
this has been copied to cncfci

**Pull request merged**
