### PR TITLE
Updating Tab Container to JS solution

### PR DESCRIPTION
**Pull request by thetwopct**
WRT https://github.com/lfph/lfph.io/issues/76 I tried to implement a CSS only solution, but sticky+overflow is not possible without JS.

In this PR:
- If number of sidebar nav items exceed screen height, implements scrolling section
- Keeps active nav item in view upon scroll
- Scrolls to item on load if using hash link
- Uses https://github.com/rgalus/sticky-js (I believe same script used for LFE)
- Revised spacing on some screens (related to static/sticky top nav spacing) https://github.com/lfph/lfph.io/issues/77

### CODE REVIEW

**Comment by thetwopct** [comment]
Example - https://pr-78-lfph.pantheonsite.io/join/faq/

**Comment by thetwopct** [comment]
Need to prevent scrollIntoView working on some mobile device views.

**Comment by cjyabraham** [comment]
For some reason when I try and [go to a hash](https://pr-78-lfph.pantheonsite.io/join/faq/#what-is-upstream-what-is-a-fork-what-is-a-maintainer) by loading it in a fresh incognito window, I always end up at the [first hash](https://pr-78-lfph.pantheonsite.io/join/faq/#host-a-project).

**Comment by cjyabraham** [comment]
I mentioned this but just reporting it here so I remember: bottom margin is too large when browser is less tall:
Screen Shot 2020-08-06 at 10 07 52 AM

**Comment by cjyabraham** [comment]
[This hash](https://pr-78-lfph.pantheonsite.io/join/faq/#a-lot-of-faqs) on mobile sometimes scrolls the page to here:
Screen Shot 2020-08-06 at 10 12 11 AM

And sometimes to here:
Screen Shot 2020-08-06 at 10 12 17 AM

**Comment by thetwopct** [comment]
OK, take a look now

- I think before when you were testing, the positioning wasn't working properly as different screen sizes have different positioning set. I've implemented a resize event now so this shouldn't matter.
- When accessing the page with a hash in the url in a fresh window, the Twitter embed pushed the page out of alignment as it loads for the items below it. I've added some CSS for the twitter embeds, and a slight timeout so the scroll has a delay on it and then rolls in to place.
- Fixed bottom spacing on smaller screens
- Changed how the table of content title displays so nav scrolls under it rather than with it

**Pull request merged**
