### PR TITLE
Nav update, project columns, SVG fix

### PR DESCRIPTION
**Pull request by thetwopct**
A bundle of changes in this one: 

- Fixed SVG issue for in the news #80 
- Fixed search bar not displaying correctly when nav is static #81
- Changed Project column size on mobile (I probably won't copy this to CNCF. There are too many projects there for singular column mobile view, and as the logos are smaller the spacing should look nicer)
- Prevent search button submitting when no search term was entered
- Removed iOS styling (rounded corners / webkit) on desktop search input in header nav
- Moved throttle function to JS globals (used for nav and tab container)
- Updated the nav so it works well regardless of browser/window resize

### CODE REVIEW

**Comment by thetwopct** [comment]
Continuing on from #80 I've spent some time on the news and blog featured images, mostly the media logos plus a bit of refactoring and tidying up. I felt that as the media coverage excerpts where often quite long, it seemed to look better when the logo was aligned to the top. Let me know your thoughts.

**Comment by cjyabraham** [comment]
> Continuing on from #80 I've spent some time on the news and blog featured images, mostly the media logos plus a bit of refactoring and tidying up. I felt that as the media coverage excerpts where often quite long, it seemed to look better when the logo was aligned to the top. Let me know your thoughts.

I agree and had the same thought at one point.

**Comment by cjyabraham** [comment]
- The first time I click the search magnifying glass nothing happens.  I always have to click it twice to get the bar to drop down.  It seems that `$( '.search-bar:visible' ).length` starts out as 1 when it should be 0.

Note for myself: will need to regenerate thumbnails again.

**Comment by thetwopct** [comment]
> * The first time I click the search magnifying glass nothing happens.  I always have to click it twice to get the bar to drop down.

Ah. That is now fixed.

**Pull request merged**
