### PR TITLE
Theme sync from CNCF

### LINKED ISSUE #95: Default thumbnail not aligned on blog
2020-12-16-150245@2x

The top thumbnail seems to be aligned to the top

### LINKED ISSUE #96: Perform a code sync with the CNCF codebase to bring the latest updates across

### LINKED ISSUE #97: Spacer blocks overlapping with other blocks in the editor
Spacer blocks seem to have other blocks overlapping with them.  See [this post](https://www.lfph.io/wp/wp-admin/post.php?post=1222&action=edit).  It doesn't stop you from editing but it doesn't look right:
Screen Shot 2021-01-12 at 8 28 36 AM

### PR DESCRIPTION
**Pull request by thetwopct**
Theme sync between CNCF and LFPH, closes #96 
Alignment of default thumbnail checking, closes #95
Updating Spacer editor styles, closes #97

I've spotted an issue with the alignment of some of the blocks in editor view. The issue is not replicated on the front end. 
2021-03-08-002721@2x

WP 5.7 is out tomorrow, and I'd like to look at that problem after we upgrade together with the CNCF editor issues.

### CODE REVIEW

**Comment by cjyabraham** [comment]
The margin issue in the editor is problematic as, when I have both left and right sidebar visible, as I normally do, some of the text goes out of view so I can't edit it properly.  So let's upgrade tomorrow and fix this before deploying.  The buttons are also too close together here on [the homepage edit screen](https://pr-100-lfph.pantheonsite.io/wp/wp-admin/post.php?post=7&action=edit).  Both of these issues are not a problem on the production instance:
Screen Shot 2021-03-08 at 2 06 59 PM

FYI, I've reopened [this issue](https://github.com/cncf/cncf.io/issues/354) which is a problem on LFPH as well but not necessary to fix in order to deploy.

Everything else seems to be good.

**Comment by thetwopct** [comment]
- Revised the way Editor displays blocks. They are now 100% width left aligned - instead of the blocks being suspended in the middle of the editor. This works better with our "max width" styles applied to paragraphs and headings, but means that full width blocks are harder to visualise in the editor. 

- Moved all the Block Styles from PHP to JS. This *feels* like it helps the performance of the editor loading, and it makes sense to me to have block styles and variations in one place.

- Unregistered a few extra core blocks that the editors don't need access too

- Updated to WP 5.7

- Spent some time to get to the bottom of list blocks, should close https://github.com/cncf/cncf.io/issues/354

**Comment by cjyabraham** [comment]
The editor feels a lot more solid.  Great!

One minor issue with lists: in this image [from the homepage](https://pr-100-lfph.pantheonsite.io/wp/wp-admin/post.php?post=7&action=edit) there are three lists.  The first one (in a group with background color) is indented too far left.  The second one (not in a group) is good and is the only one where indentation matches the front-end.  The third one (in a group with no background color) is indented too far left such that you can't see the bullets.  Can you fix lists in groups so that they don't go too far left?
Screen Shot 2021-03-12 at 1 08 19 PM

**Comment by thetwopct** [comment]
Seems to be a group problem - it only happens when the group has no color. When a color is added, so is padding - not sure why they do that tbh 🤷 

```
.wp-block-group.has-background {
    padding: 1.25em 2em;
}

```
I've added a consistent padding to all groups that matches the padding of a block sans group, and I think this aligns the lists now:

2021-03-12-113718@2x

I can foresee other full width blocks like columns and media/text also having this issue, but unless its a problem lets not go looking for these foibles.

**Pull request merged**
