### PR TITLE
Improving newsroom code

### PR DESCRIPTION
**Pull request by thetwopct**
Was working on https://github.com/lfph/lfph.io/issues/74 and noticed a few other issues with newsroom so decided to fix those along with a refactor/tidy.

- Fixed default thumbnail issues so the SVG is centered https://github.com/lfph/lfph.io/issues/74
- Changed aspect of images so scaling is improved and more consistent
- Removed expanded view https://github.com/lfph/lfph.io/issues/73
- Reworked the date + author line so it wraps nicely (for instance if authors name is long)
- Amended "sticky"/featured skew tag
- Slight amendments to columns and spacing within archive pages

I had to amend the LF MU plugin slightly, so if this is pulled in to live before this PR is merged default images may break (although I don't think there are any currently on LFPH)

### CODE REVIEW

**Comment by thetwopct** [comment]
Pages using the archive page:

Home (News) - https://pr-79-lfph.pantheonsite.io
Blog - https://pr-79-lfph.pantheonsite.io/blog/
In the News - https://pr-79-lfph.pantheonsite.io/news/
Search - https://pr-79-lfph.pantheonsite.io/?s=test

**Comment by cjyabraham** [comment]
Looks good.  Can you LMK when this is finalized and I'll do a final review and merge?

**Comment by cjyabraham** [comment]
I like most of the changes.  

It looks like the dateline and byline are now on [two different lines here](https://pr-79-lfph.pantheonsite.io/2020/07/20/join-with-us-at-linux-foundation-public-health/) whereas I think they look better on [the same line as on the live site](https://www.lfph.io/2020/07/20/join-with-us-at-linux-foundation-public-health/).

**Comment by thetwopct** [comment]
Ah not intentional, have reverted the styling for that. Anything else? (p.s. Pantheon issues seems to have borked the above build)

**Comment by cjyabraham** [comment]
CircleCI seems to be having [issues with npm](https://status.circleci.com/)...

**Comment by cjyabraham** [comment]
Do we need to regenerate thumbnails when we deploy?

**Comment by thetwopct** [comment]
> Do we need to regenerate thumbnails when we deploy?

Yes, these image names have changed

- newsroom-260
- newsroom-325
- newsroom-540
- newsroom-600
- newsroom-1200

```
# only missing (it should pick up the dimensions have changed)
terminus wp lfph.live -- media regenerate --only-missing --yes

# per image size (dont think you can do multiple in 1 line)
terminus wp lfph.live -- media regenerate --image_size=newsroom-260 --yes
terminus wp lfph.live -- media regenerate --image_size=newsroom-325 --yes
terminus wp lfph.live -- media regenerate --image_size=newsroom-540 --yes
terminus wp lfph.live -- media regenerate --image_size=newsroom-600 --yes
terminus wp lfph.live -- media regenerate --image_size=newsroom-1200 --yes

# just do everything
terminus wp lfph.live -- media regenerate --yes
```

**Pull request merged**
